# Build phase
FROM node:20-alpine AS builder
WORKDIR /app
COPY client/package*.json ./client/
COPY shared/ ./shared/
WORKDIR /app/client
RUN npm install
COPY client/ ./
RUN npm run build

# Execution phase
FROM nginx:alpine
COPY --from=builder /app/client/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
