# Build phase
FROM node:20-alpine AS builder
WORKDIR /app
COPY admin/package*.json ./admin/
COPY shared/ ./shared/
WORKDIR /app/admin
RUN npm install
COPY admin/ ./
RUN npm run build

# Execution phase
FROM nginx:alpine
COPY --from=builder /app/admin/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
